fpath=(
	"$ZDOTDIR/functions"
	"$ZDOTDIR/functions"/*(N/)
	"$ZDOTDIR/completions"
	$fpath
)

autoload_dir() {
	for f in "$1"/*(N.); do
		autoload -Uz "${f:t}"
	done
}

autoload_dir "$ZDOTDIR/functions"
for d in "$ZDOTDIR/functions"/*(N/); do
	autoload_dir "$d"
done

for f in "$ZDOTDIR/conf.d"/*.zsh(N); do
	source "$f"
done

unset -f autoload_dir
