FROM node:26-trixie-slim

RUN : \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
    bash \
    ca-certificates \
    git \
    curl \
    build-essential \
    clang \
    mold \
    pkg-config \
    sudo \
    ripgrep \
    jq \
    vim \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN npm install -g --ignore-scripts @earendil-works/pi-coding-agent

ARG USER_NAME
ARG UID
ARG GID
ARG HOME
ARG CARGO_HOME
ARG RUSTUP_HOME
ARG CARGO_INCREMENTAL

RUN : \
  && userdel node \
  && groupadd -g "$GID" "$USER_NAME" \
  && useradd -l -u "$UID" -g "$GID" \
	-G sudo --shell /bin/bash --create-home "$USER_NAME" \
  && printf '%s ALL=(ALL) NOPASSWD: ALL\n' "$USER_NAME" \
	> "/etc/sudoers.d/$USER_NAME"

ENV \
  PATH="$CARGO_HOME/bin:$PATH" \
  CARGO_HOME="$CARGO_HOME" \
  RUSTUP_HOME="$RUSTUP_HOME" \
  CARGO_INCREMENTAL="$CARGO_INCREMENTAL"

USER $USER_NAME
WORKDIR $HOME
